import { v4 as uuidv4 } from "uuid";
import { PDFPage } from "./types";

// Demo templates
export const createBrochureTemplate = (): PDFPage[] => {
  const page1Id = uuidv4();
  const page2Id = uuidv4();

  return [
    // Cover page
    {
      id: page1Id,
      background: "https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=600&auto=format",
      elements: [
        {
          id: uuidv4(),
          type: "rectangle",
          position: { x: 0, y: 0 },
          size: { width: 200, height: 842 },
          zIndex: 1,
          backgroundColor: "rgba(59, 130, 246, 0.9)",
          borderColor: "#3b82f6",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 30, y: 300 },
          size: { width: 140, height: 200 },
          zIndex: 2,
          content: "PRODUCT BROCHURE",
          fontFamily: "Arial",
          fontSize: 24,
          fontWeight: "bold",
          color: "#ffffff",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 250, y: 300 },
          size: { width: 300, height: 80 },
          zIndex: 2,
          content: "Company Name",
          fontFamily: "Arial",
          fontSize: 36,
          fontWeight: "bold",
          color: "#ffffff",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 250, y: 380 },
          size: { width: 300, height: 60 },
          zIndex: 2,
          content: "Product Tagline Goes Here",
          fontFamily: "Arial",
          fontSize: 18,
          fontWeight: "normal",
          color: "#ffffff",
          textAlign: "left",
        },
      ],
    },
    // Content page
    {
      id: page2Id,
      elements: [
        {
          id: uuidv4(),
          type: "rectangle",
          position: { x: 0, y: 0 },
          size: { width: 20, height: 842 },
          zIndex: 1,
          color: "#3b82f6",
          width: 20,
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 50 },
          size: { width: 500, height: 60 },
          zIndex: 2,
          content: "Product Features",
          fontFamily: "Arial",
          fontSize: 24,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "image",
          position: { x: 50, y: 120 },
          size: { width: 240, height: 180 },
          zIndex: 2,
          src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&auto=format",
          alt: "Product image",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 320, y: 120 },
          size: { width: 240, height: 180 },
          zIndex: 2,
          content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget ultricies tincidunt, nisl nisl aliquam nisl, eget ultricies nisl nisl eget nisl.",
          fontFamily: "Arial",
          fontSize: 14,
          fontWeight: "normal",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 350 },
          size: { width: 500, height: 60 },
          zIndex: 2,
          content: "Benefits",
          fontFamily: "Arial",
          fontSize: 24,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "table",
          position: { x: 50, y: 420 },
          size: { width: 500, height: 200 },
          zIndex: 2,
          data: [
            ["Benefit", "Description"],
            ["Quality", "Premium materials and craftsmanship"],
            ["Performance", "Industry-leading specifications"],
            ["Support", "24/7 customer service"],
          ],
          headerRow: true,
          borderColor: "#cccccc",
        },
      ],
    },
  ];
};

export const createDataSheetTemplate = (): PDFPage[] => {
  return [
    {
      id: uuidv4(),
      elements: [
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 50 },
          size: { width: 500, height: 60 },
          zIndex: 2,
          content: "Product Data Sheet",
          fontFamily: "Arial",
          fontSize: 28,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "center",
        },
        {
          id: uuidv4(),
          type: "rectangle",
          position: { x: 50, y: 120 },
          size: { width: 500, height: 2 },
          zIndex: 1,
          backgroundColor: "#3b82f6",
          borderColor: "#3b82f6",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: uuidv4(),
          type: "table",
          position: { x: 50, y: 150 },
          size: { width: 500, height: 150 },
          zIndex: 2,
          data: [
            ["Specification", "Value"],
            ["Dimensions", '10" x 5" x 2"'],
            ["Weight", "2.5 lbs"],
            ["Material", "Aluminum"],
            ["Power", "120V AC, 60Hz"],
          ],
          headerRow: true,
          borderColor: "#cccccc",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 330 },
          size: { width: 500, height: 40 },
          zIndex: 2,
          content: "Performance Metrics",
          fontFamily: "Arial",
          fontSize: 20,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "chart",
          position: { x: 50, y: 380 },
          size: { width: 500, height: 250 },
          zIndex: 2,
          chartType: "bar",
          data: {
            labels: ["Q1", "Q2", "Q3", "Q4"],
            datasets: [
              {
                label: "Performance",
                data: [65, 78, 80, 94],
                backgroundColor: "rgba(59, 130, 246, 0.7)",
                borderColor: "#3b82f6",
              },
            ],
          },
          options: {
            showLegend: true,
            legendPosition: "top",
            showGrid: true,
          },
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 650 },
          size: { width: 500, height: 80 },
          zIndex: 2,
          content: "For more information, contact support@company.com",
          fontFamily: "Arial",
          fontSize: 14,
          fontWeight: "normal",
          color: "#666666",
          textAlign: "center",
        },
      ],
    },
  ];
};

export const createCaseStudyTemplate = (): PDFPage[] => {
  return [
    {
      id: uuidv4(),
      elements: [
        {
          id: uuidv4(),
          type: "image",
          position: { x: 50, y: 50 },
          size: { width: 240, height: 160 },
          zIndex: 2,
          src: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&auto=format",
          alt: "Case study image",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 320, y: 50 },
          size: { width: 240, height: 60 },
          zIndex: 2,
          content: "CASE STUDY",
          fontFamily: "Arial",
          fontSize: 28,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 320, y: 120 },
          size: { width: 240, height: 40 },
          zIndex: 2,
          content: "Client: ACME Corporation",
          fontFamily: "Arial",
          fontSize: 16,
          fontWeight: "bold",
          color: "#666666",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 320, y: 160 },
          size: { width: 240, height: 40 },
          zIndex: 2,
          content: "Industry: Technology",
          fontFamily: "Arial",
          fontSize: 16,
          fontWeight: "normal",
          color: "#666666",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "rectangle",
          position: { x: 50, y: 240 },
          size: { width: 500, height: 2 },
          zIndex: 1,
          backgroundColor: "#3b82f6",
          borderColor: "#3b82f6",
          borderWidth: 0,
          borderRadius: 0,
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 270 },
          size: { width: 500, height: 40 },
          zIndex: 2,
          content: "Challenge",
          fontFamily: "Arial",
          fontSize: 20,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 320 },
          size: { width: 500, height: 100 },
          zIndex: 2,
          content: "ACME Corporation needed to streamline their workflow process while maintaining data security and compliance with industry regulations.",
          fontFamily: "Arial",
          fontSize: 14,
          fontWeight: "normal",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 430 },
          size: { width: 500, height: 40 },
          zIndex: 2,
          content: "Solution",
          fontFamily: "Arial",
          fontSize: 20,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 480 },
          size: { width: 500, height: 150 },
          zIndex: 2,
          content:
            "We implemented our enterprise platform with custom workflows and security features tailored to ACMEs specific needs. The solution included automated approval processes, audit trails, and encrypted data storage.",
          fontFamily: "Arial",
          fontSize: 14,
          fontWeight: "normal",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "text",
          position: { x: 50, y: 640 },
          size: { width: 500, height: 40 },
          zIndex: 2,
          content: "Results",
          fontFamily: "Arial",
          fontSize: 20,
          fontWeight: "bold",
          color: "#333333",
          textAlign: "left",
        },
        {
          id: uuidv4(),
          type: "chart",
          position: { x: 50, y: 690 },
          size: { width: 500, height: 140 },
          zIndex: 2,
          chartType: "bar",
          data: {
            labels: ["Efficiency", "Cost Savings", "Compliance"],
            datasets: [
              {
                label: "Improvement",
                data: [45, 32, 80],
                backgroundColor: ["#4BC0C0", "#FFCE56", "#36A2EB"],
                borderColor: ["#3DA8A8", "#E6B94F", "#3092D2"],
              },
            ],
          },
          options: {
            showLegend: false,
            showGrid: true,
          },
        },
      ],
    },
  ];
};
